language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sanchitd9/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sanchitd9/react-test npm test

after_success:
  - docker build -t sanchitd9/react-client ./client
  - docker build -t sanchitd9/react-nginx ./nginx
  - docker build -t sanchitd9/react-express-server ./server
  - docker build -t sanchitd9/react-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sanchitd9/react-client
  - docker push sanchitd9/react-nginx
  - docker push sanchitd9/react-express-server
  - docker push sanchitd9/react-worker

deploy:
  region: "us-east-2"
  app: "multi-container-react"
  env: "Multi-container-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-959704192009"
  bucket_path: "multi-container-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY