sudo: required
services:
  - docker

before_install:
  - docker build -t sanchitd9/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sanchitd9/react-test npm test

after_success:
  - docker build -t sanchitd9/react-client ./client
  - docker build -t sanchitd9/react-nginx ./nginx
  - docker build -t sanchitd9/react-express-server ./server
  - docker build -t sanchitd9/react-worker ./worker